### ISSUE TITLE
extensions.py

### ISSUE THREAD

**Issue by ripnew** [dibrale/webui-autonomics#6]
Hi, sorry I am new to text-generation-webui-extensions and I am using one_click.py to install it on windows. All runs good till I try to add your extension, installed thru interface. I am getting error below about missing extensions, please let me know which version I need as if I add it only to requirements.txt and update it will download version which will corrupt my environment

01:42:27-817565 INFO     Loading the extension "webui-autonomics"
01:42:27-818565 ERROR    Failed to load the extension "webui-autonomics".
Traceback (most recent call last):
  File "X:\DIFFUSION\text-generation-webui\text-generation-webui\modules\extensions.py", line 36, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1
    import extensions.webui-autonomics.script
                           ^
SyntaxError: invalid syntax

**Comment by dibrale** [comment]
Hello @ripnew,

Thanks for trying out my extension. It's been a bit since I've updated it, so there might be a compatibility issue with the current version of ooba. However, the error looks like it might just be a naming issue. What argument are you using with the `--extensions` flag when starting `server.py`?

**Comment by ripnew** [comment]
Hi, I tried to enable it on interface first with same issue so i dont think
it is naming, I am not at my PC now so I cross check it tomorrow and let
you know

Ty for response br, R.
